### ISSUE TITLE
Possible type in 05 homework

### ISSUE THREAD

**Issue by steviol** [ckorikov/2022-fall-computer-science#3]
https://github.com/ckorikov/2022-fall-computer-science/blob/0d8b91d5e0329ed45085707afbcce614101ecadf/05_computer_architecture.md?plain=1#L54-L55

У нас уже есть эта директория с задания, и домашняя работа относится больше к цпу чем к озу. Вероятно, там должно быть `cpuinfo`?

**Comment by ckorikov** [comment]
Yes, it's typo. Fixed in 3b439a187bd8d15c9d565fae65ef40a57da89935
